on:
  push:
    branches:
      - jishiyidao

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    # 拉取github仓库代码
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    # 执行依赖安装
    - name: 安装依赖
      run: |
          npm install
        
    # 执行构建步骤
    - name: 构建
      run: |
          npm run build
    # 执行部署，将当前dist目录中的内容推送到gh-pages分支下的jishiyidao目录
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@releases/v4 # 这个action会根据配置自动推送代码到指定分支
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        branch: gh-pages  ##指定推送到的远程分支
        folder: dist # 指定构建之后要推送哪个目录的代码
        target-folder: jishiyidao